# Site
title:              Jinyi Zhou
bio:                'Salt Lake City, UT'
description:        "minimal."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.jpg'
background:         'https://upload.wikimedia.org/wikipedia/commons/7/79/%D0%A1%D0%B2%D1%96%D1%82%D0%BB%D0%BE_%D0%B2_%D0%BA%D0%B0%D0%BF%D0%BB%D0%B8%D1%87%D1%86%D1%96.jpg'
tiled_bg:           false
locale:             en_US
url:                https://jinyizh.github.io
music_intro:        '♫ My top tracks this month are: ♪'

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   jinyizh

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              jinyizhou21@gmail.com
#twitter:           username
#facebook:          username
github-url:         jinyizh
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           jinyizhou620
#xing:              username
#instagram:         username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:             username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
